tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'caskroom/versions'
tap 'thoughtbot/formulae'

brew 'curl'
brew 'git'
brew 'go'
brew 'grc', args: ['HEAD']
brew 'mackup'
brew 'mas'
brew 'node'
brew 'openssl'
brew 'python'
brew 'rbenv'
brew 'rcm'
brew 'ruby-build'
brew 'ssh-copy-id'
brew 'wget'
brew 'zsh'
brew 'zsh-completions'
brew 'zsh-syntax-highlighting'

cask 'bartender'
cask 'caffeine'
cask 'docker'
cask 'dropbox'
cask 'flux'
cask 'font-hack'
cask 'google-chrome'
cask 'google-drive'
cask 'iterm2'
cask 'java'
cask 'mac2imgur'
cask 'mplayerx'
cask 'numi'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlstephen'
cask 'skype'
cask 'slate'
cask 'sourcetree'
cask 'sublime-text'
cask 'telegram-desktop'
cask 'the-unarchiver'
cask 'transmission'
cask 'vagrant'
cask 'vagrant-manager'
cask 'virtualbox'

mas '1Password', id: 443987910
mas 'DaisyDisk', id: 411643860
mas 'ForkLift', id: 412448059
mas 'Wunderlist', id: 410628904
