#!/bin/sh

# Ask for sudo and keep it alive
sudo -v
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Misc
# ---------------------------------------

# Disable Resume system-wide
defaults write NSGlobalDomain NSQuitAlwaysKeepsWindows -bool false

# Enable full keyboard access for all controls
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

# Disable the "Are you sure you want to open this application?" dialog
defaults write com.apple.LaunchServices LSQuarantine -bool false

# Time Machine
# ---------------------------------------

# Disable local backups
hash tmutil &> /dev/null && sudo tmutil disablelocal

# Don't offer new disks for backup
defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

# Finder
# ---------------------------------------

# Show path bar
defaults write com.apple.finder ShowPathbar -bool true

# Search in current folder by default
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
