call plug#begin('~/.vim/plugged')

Plug 'airblade/vim-gitgutter'
Plug 'bling/vim-airline'
Plug 'chriskempson/base16-vim'
Plug 'editorconfig/editorconfig-vim'
Plug 'ervandew/supertab'
Plug 'honza/vim-snippets'
Plug 'jeetsukumaran/vim-buffergator'
Plug 'jiangmiao/auto-pairs'
Plug 'kchmck/vim-coffee-script'
Plug 'kien/ctrlp.vim'
Plug 'rking/ag.vim'
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/nerdtree'
Plug 'sirver/ultisnips'
Plug 'slim-template/vim-slim'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rails'
Plug 'tpope/vim-surround'
Plug 'xuyuanp/nerdtree-git-plugin'
Plug 'yggdroot/indentline'

call plug#end()

colorscheme base16-eighties

set number
set numberwidth=5

set nobackup
set nowritebackup
set noswapfile
set autowrite

set ruler
set colorcolumn=80

set wrap
set cpo=n

set laststatus=2

set hlsearch
set incsearch
set ignorecase
set smartcase

set autoindent
set smartindent

set complete=.,b,u,]
set wildmenu

set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab

set backspace=2

let g:NERDSpaceDelims = 1

if executable('ag')
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g "" --ignore "\.git$"'
  let g:ctrlp_use_caching = 0
endif

map <C-n> :NERDTreeToggle<CR>

vmap <F5> :sort<CR>
