#!/usr/bin/env bash

set -euo pipefail

source "$HOME/.restic/env.bash"

_say() {
  printf "[%s] %s\n" "$(date +"%Y-%m-%d %H:%M:%S")" "$1"
}

_restic() {
  /opt/homebrew/bin/restic "$@"
}

_say "Starting cleanup"
printf "\n"

for arg in "$@"; do
  if [ "$arg" == "--unlock" ]; then
    _restic unlock
  fi
done

_restic forget \
  --host="$RESTIC_HOST" \
  --keep-within-hourly=1d \
  --keep-within-daily=7d \
  --keep-within-weekly=1m \
  --keep-within-monthly=1y \
  --keep-within-yearly=100y

_restic prune

_restic check

printf "\n"
_say "Cleanup finished"
